apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  labels:
    app: url-shortener
data:
  REDIS_HOST: redis-master.cache.svc.cluster.local
  REDIS_PORT: "6379"
  REDIS_PASSWORD: UrlShortRedis2025
